version: '3'

services:
  database:
    image: postgres:10.4
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  database_init:
    build: _database_init
    command: /app/container-entrypoint-db_init.sh
    depends_on:
      - database
    env_file:
      - .env


  benchmark_dj:
    build: django
    command: /app/container-entrypoint-django.sh
    working_dir: /app/benchmark_dj/
    env_file:
      - .env
    ports:
      - "9001:8000"
    depends_on:
      - database_init


  benchmark_tornado:
    build: tornado
    command: /app/container-entrypoint-tornado.sh
    env_file:
      - .env
    ports:
      - "9002:8000"
    depends_on:
      - database_init


  benchmark_flask:
    build: flask
    command: /app/container-entrypoint-flask.sh
    env_file:
      - .env
    ports:
      - "9003:8000"
    depends_on:
      - database_init

  benchmark_fastapi_sqlalchemy_async:
    build: fastapi-sqlalchemy-async
    command: /app/container-entrypoint-fastapi-sqlalchemy-async.sh
    env_file:
      - .env
    ports:
      - "9004:8000"
    depends_on:
      - database_init





